### ISSUE TITLE
Suggestions in joins

### ISSUE THREAD

**Issue by talegari** [talegari/tidypandas#29]
@grahitr Please review:

1. Allow user to control both suffix (x and y) -- right now only y is controllable. Defaults can be `["", "_y"]` as it is currently there.
2. If join columns differ in name, keep both left and right side ones. There no danger of loosing the data ever and keeps it simple for the user. This will keep the `keep` argument out which is primarily to maintain dplyr's back compatibility (we dont have to worry on this).

**Comment by grahitr** [comment]
> @grahitr Please review:
> 
>     1. Allow user to control both suffix (x and y) -- right now only y is controllable. Defaults can be `["", "_y"]` as it is currently there.
> 
>     2. If join columns differ in name, keep both left and right side ones. There no danger of loosing the data ever and keeps it simple for the user. This will keep the `keep` argument out which is primarily to maintain dplyr's back compatibility (we dont have to worry on this).

Both of these look correct to me.

**Comment by talegari** [comment]
@grahitr  Please review and merge:
https://github.com/talegari/tidypandas/pull/30
