### ISSUE TITLE
datar package

### ISSUE THREAD

**Issue by pwwang** [talegari/tidypandas#3]
Hi,

Great effort!
Have you checked out [`datar`](https://github.com/pwwang/datar), which does a similar thing but with a more complete implementation?

Let me know your comments or any chance to collaborate.

**Comment by talegari** [comment]
@pwwang `datar` is a good design and implementation. As of tidypandas, we will soon making a release.

As of the differences are concerned, one thing I wonder how a `datar` user would do programmatically like `iris >> distinct(f.Species)` where lets say user has the string 'Species'?

**Comment by pwwang** [comment]
```python
col = "Species"
iris >> distinct(f[col])
```

**Comment by talegari** [comment]
Thank you, this is great! May be I missed this in the documentation.
